name: Deploy EC2
 
on:
  push:
    branches:
      - main
   
jobs:
  deploy:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
         
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0166fe664262f664c \
            --instance-type t2.micro \
            --security-group-ids sg-02acdbda385a1243e \
            --subnet-id subnet-058881bcf950f863b \
            --key-name rsa-Cursodevops \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "Waiting for Public IP to be assigned..."
          sleep 60  # Espera para que la instancia se inicie y reciba una IP pública
          INSTANCE_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
         
      - name: Print IP Address
        run: echo "Instance IP is $INSTANCE_IP"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* ec2-user@${{ env.INSTANCE_IP }}:/home/ec2-user/app

      - name: Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ env.INSTANCE_IP }} "
            sudo yum update -y
            sudo yum install -y yum-utils
            curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
            sudo yum install -y coreutils
            cd /home/ec2-user/app
            npm install
            nohup node app.js > app.log 2>&1 &"
